version: "3.9"
services:
  postgres:
    container_name: postgres_container1
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=ecommerce
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5440:5432"

  pgadmin:
    container_name: pgadmin_container1
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=petronikolosn@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5051:80"

volumes:
  postgres:
  pgadmin:
